version: "3"
services:
  reverseproxy:
<<<<<<< HEAD
      image: reverseproxy:v3
=======
      image: reverseproxy
>>>>>>> deploy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - api-user
        - api-feed
  api-user:
<<<<<<< HEAD
    image: udagram-api-user:v3
=======
    image: udagram-api-user
>>>>>>> deploy
    environment:
      POSTGRES_USERNAME: mizile
      POSTGRES_PASSWORD: mizile123
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres.cu50d2w51m7p.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: udacitybucket99
      JWT_SECRET: testing
      URL: "http://localhost:8100"
  api-feed:
<<<<<<< HEAD
    image: udagram-api-feed:v3
=======
    image: udagram-api-feed
>>>>>>> deploy
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: mizile
      POSTGRES_PASSWORD: mizile123
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres.cu50d2w51m7p.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: udacitybucket99
      JWT_SECRET: testing
      URL: "http://localhost:8100"
  frontend:
<<<<<<< HEAD
    image: udagram-frontend:v3
=======
    image: udagram-frontend
>>>>>>> deploy
    ports:
      - "8100:80"
