version: 2.1
jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz
            sudo tar -xvf node-v18.0.0-linux-x64.tar.xz
            sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/
            node --version => v18.0.0
            sudo apt install nodejs
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed mizile/udagram-api-feed:v3
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user mizile/udagram-api-user:v3
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend mizile/udagram-frontend:v3
            docker build -t reverseproxy ./udagram-reverseproxy
            docker tag reverseproxy mizile/reverseproxy:v3
            echo "-------- All images succesfully built----------"
            echo " ------- login in to hub--------"
            docker login -u mizile -p $DOCKERPASS
            echo "-------------- Pushing images to dockerhub-------"
            docker push mizile/udagram-api-feed:v3
            docker push mizile/udagram-api-user:v3
            docker push mizile/udagram-frontend:v3
            docker push mizile/reverseproxy:v3
workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]