version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- Installing dependencies-----------"
            sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz
            sudo tar -xvf node-v18.0.0-linux-x64.tar.xz
            sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/
            node --version => v18.0.0
            sudo apt install nodejs
            echo "--------- The images is Building ------------"
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed mizile/udagram-api-feed:v3a
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user mizile/udagram-api-user:v3a
            
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend mizile/udagram-frontend:local
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy mizile/udagram-reverseproxy:v3a
            echo "-------- All images succesfully built----------"
            echo " ------- login in to hub--------"
            docker login -u mizile -p $DOCKERPASS
            echo "-------------- Pushing images to dockerhub-------"
            docker push mizile/udagram-api-feed:v3a
            docker push mizile/udagram-api-user:v3a
            docker push mizile/udagram-frontend:local
            docker push mizile/udagram-reverseproxy:v3a
workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]
